In [2]:
import numpy as np
population=np.random.randint(
    1,
    100,
    10000
 )

sample_means=[]

for i in range(500):
  sample=np.random.choice(population,30)

  sample_means.append(np.mean(sample))

print(sample_means[:20])

[np.float64(46.06666666666667), np.float64(46.5), np.float64(52.6), np.float64(41.7), np.float64(47.7), np.float64(45.9), np.float64(54.86666666666667), np.float64(50.93333333333333), np.float64(48.8), np.float64(48.766666666666666), np.float64(53.1), np.float64(39.6), np.float64(48.233333333333334), np.float64(44.53333333333333), np.float64(49.13333333333333), np.float64(48.3), np.float64(60.0), np.float64(57.166666666666664), np.float64(53.56666666666667), np.float64(54.93333333333333)]

In [3]:
human_heights=[120,150,155,160,165,170,175,180,185,190,210]


# most people are around 170
# very few has 140

# or very few has  210



# *
#     ***
#     ****
#     *****
#     ******
#               *

In [4]:
#  mean= median =mode
#   its called normal because  many natural phenomena follows it

#height,weight,IQ,examscores,blood pressure

In [5]:
import numpy as np
data=np.random.normal(
    50,10,1000
)

print(data[:20])

[59.66366556 68.07436255 36.68320331 45.60617043 57.77532266 50.96068183
 49.6994047  52.64222677 42.37793911 35.37614966 47.00830546 38.91525744
 58.52231223 62.33656772 34.31133392 53.72202689 46.28276115 77.22139053
 54.31145396 55.90458612]

In [6]:
import numpy as np
population=np.random.randint(
    1,100,10000
)

print(population[:20])

[48 25 36 30 43 54 13 26 16 19 89  4 33 59 64 51 90  9 49 35]

In [7]:
sample=np.random.choice(population,
                        30)
print(sample)

[78 56 68 62 88 63 32 37 34 63 38 28 69 14 40 39 33 46 55 57 79  8 88 33
 51  2 69 42 48 22]

In [8]:
print(np.mean(sample))

48.06666666666667

In [10]:
import numpy as np
population=np.random.randint(
    1,100,10000
)
sample_means=[]
for i in range(100):
  sample=np.random.choice(population,30)
  mean=np.mean(sample)
  sample_means.append(mean)
print(sample_means)

[np.float64(46.1), np.float64(51.63333333333333), np.float64(53.766666666666666), np.float64(56.833333333333336), np.float64(54.8), np.float64(51.833333333333336), np.float64(49.86666666666667), np.float64(48.86666666666667), np.float64(56.166666666666664), np.float64(52.93333333333333), np.float64(37.833333333333336), np.float64(52.666666666666664), np.float64(50.833333333333336), np.float64(52.86666666666667), np.float64(49.53333333333333), np.float64(51.9), np.float64(43.93333333333333), np.float64(57.666666666666664), np.float64(49.86666666666667), np.float64(51.13333333333333), np.float64(47.9), np.float64(52.56666666666667), np.float64(47.266666666666666), np.float64(56.7), np.float64(40.7), np.float64(51.766666666666666), np.float64(45.833333333333336), np.float64(53.733333333333334), np.float64(42.2), np.float64(50.36666666666667), np.float64(54.86666666666667), np.float64(51.733333333333334), np.float64(52.266666666666666), np.float64(51.03333333333333), np.float64(47.63333333333333), np.float64(44.1), np.float64(46.233333333333334), np.float64(50.93333333333333), np.float64(48.1), np.float64(49.1), np.float64(50.46666666666667), np.float64(51.7), np.float64(54.06666666666667), np.float64(44.36666666666667), np.float64(50.43333333333333), np.float64(47.6), np.float64(51.3), np.float64(48.266666666666666), np.float64(44.333333333333336), np.float64(43.4), np.float64(54.766666666666666), np.float64(49.93333333333333), np.float64(42.36666666666667), np.float64(53.6), np.float64(55.53333333333333), np.float64(47.56666666666667), np.float64(47.7), np.float64(49.2), np.float64(40.96666666666667), np.float64(44.7), np.float64(49.56666666666667), np.float64(53.63333333333333), np.float64(46.53333333333333), np.float64(53.13333333333333), np.float64(52.266666666666666), np.float64(43.166666666666664), np.float64(48.1), np.float64(55.46666666666667), np.float64(59.2), np.float64(44.2), np.float64(62.6), np.float64(45.43333333333333), np.float64(60.7), np.float64(39.7), np.float64(43.2), np.float64(52.4), np.float64(53.2), np.float64(49.43333333333333), np.float64(50.3), np.float64(46.1), np.float64(59.13333333333333), np.float64(49.06666666666667), np.float64(44.43333333333333), np.float64(54.666666666666664), np.float64(54.4), np.float64(45.06666666666667), np.float64(45.233333333333334), np.float64(45.5), np.float64(58.3), np.float64(54.93333333333333), np.float64(56.166666666666664), np.float64(51.666666666666664), np.float64(49.833333333333336), np.float64(43.93333333333333), np.float64(45.53333333333333), np.float64(50.46666666666667), np.float64(55.53333333333333), np.float64(53.7), np.float64(51.766666666666666), np.float64(50.7)]

In [11]:
#why cant we use just one sample?
#one sample may be lukcy or unlucky
#we will take many samples given stability

In [13]:
import pandas as pd

data = {

    "StudentID":[
        101,102,103,104,105,
        106,107,108,109,110,
        111,112,113,114,115,
        116,117,118,119,120
    ],

    "Name":[
        "Ram","Sita","John","Priya","Arjun",
        "Sneha","David","Kiran","Ravi","Meena",
        "Akash","Pooja","Rahul","Divya","Ramesh",
        "Anjali","Vijay","Keerthi","Karthik","Nisha"
    ],

    "Gender":[
        "Male","Female","Male","Female","Male",
        "Female","Male","Male","Male","Female",
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Department":[
        "CSE","ECE","IT","CSE","MECH",
        "ECE","IT","CSE","MECH","IT",
        "CSE","ECE","IT","MECH","CSE",
        "ECE","IT","MECH","CSE","ECE"
    ],

    "City":[
        "Hyderabad","Bangalore","Chennai","Mumbai","Hyderabad",
        "Bangalore","Chennai","Mumbai","Hyderabad","Bangalore",
        "Chennai","Mumbai","Hyderabad","Bangalore","Chennai",
        "Mumbai","Hyderabad","Bangalore","Chennai","Mumbai"
    ],

    "Age":[
        20,21,22,20,23,
        21,22,20,23,21,
        22,20,21,23,22,
        20,21,22,23,20
    ],

    "Marks":[
        85,78,90,67,55,
        88,92,45,60,73,
        95,81,69,58,84,
        76,91,62,87,79
    ],

    "Attendance":[
        92,88,95,75,68,
        90,97,60,72,80,
        98,91,77,70,89,
        85,96,74,93,87
    ],

    "Placement":[
        "Yes","No","Yes","No","No",
        "Yes","Yes","No","No","Yes",
        "Yes","Yes","No","No","Yes",
        "Yes","Yes","No","Yes","Yes"
    ]
}

df = pd.DataFrame(data)
df

,StudentID,Name,Gender,Department,City,Age,Marks,Attendance,Placement
0,101,Ram,Male,CSE,Hyderabad,20,85,92,Yes
1,102,Sita,Female,ECE,Bangalore,21,78,88,No
2,103,John,Male,IT,Chennai,22,90,95,Yes
3,104,Priya,Female,CSE,Mumbai,20,67,75,No
4,105,Arjun,Male,MECH,Hyderabad,23,55,68,No
5,106,Sneha,Female,ECE,Bangalore,21,88,90,Yes
6,107,David,Male,IT,Chennai,22,92,97,Yes
7,108,Kiran,Male,CSE,Mumbai,20,45,60,No
8,109,Ravi,Male,MECH,Hyderabad,23,60,72,No
9,110,Meena,Female,IT,Bangalore,21,73,80,Yes
10,111,Akash,Male,CSE,Chennai,22,95,98,Yes
11,112,Pooja,Female,ECE,Mumbai,20,81,91,Yes
12,113,Rahul,Male,IT,Hyderabad,21,69,77,No
13,114,Divya,Female,MECH,Bangalore,23,58,70,No
14,115,Ramesh,Male,CSE,Chennai,22,84,89,Yes
15,116,Anjali,Female,ECE,Mumbai,20,76,85,Yes
16,117,Vijay,Male,IT,Hyderabad,21,91,96,Yes
17,118,Keerthi,Female,MECH,Bangalore,22,62,74,No
18,119,Karthik,Male,CSE,Chennai,23,87,93,Yes
19,120,Nisha,Female,ECE,Mumbai,20,79,87,Yes

In [14]:
import pandas as pd

data = {

    "StudentID":[
        101,102,103,104,105,
        106,107,108,109,110,
        111,112,113,114,115,
        116,117,118,119,120
    ],

    "Name":[
        "Ram","Sita","John","Priya","Arjun",
        "Sneha","David","Kiran","Ravi","Meena",
        "Akash","Pooja","Rahul","Divya","Ramesh",
        "Anjali","Vijay","Keerthi","Karthik","Nisha"
    ],

    "Gender":[
        "Male","Female","Male","Female","Male",
        "Female","Male","Male","Male","Female",
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Department":[
        "CSE","ECE","IT","CSE","MECH",
        "ECE","IT","CSE","MECH","IT",
        "CSE","ECE","IT","MECH","CSE",
        "ECE","IT","MECH","CSE","ECE"
    ],

    "City":[
        "Hyderabad","Bangalore","Chennai","Mumbai","Hyderabad",
        "Bangalore","Chennai","Mumbai","Hyderabad","Bangalore",
        "Chennai","Mumbai","Hyderabad","Bangalore","Chennai",
        "Mumbai","Hyderabad","Bangalore","Chennai","Mumbai"
    ],

    "Age":[
        20,21,22,20,23,
        21,22,20,23,21,
        22,20,21,23,22,
        20,21,22,23,20
    ],

    "Marks":[
        85,78,90,67,55,
        88,92,45,60,73,
        95,81,69,58,84,
        76,91,62,87,79
    ],

    "Attendance":[
        92,88,95,75,68,
        90,97,60,72,80,
        98,91,77,70,89,
        85,96,74,93,87
    ],

    "Placement":[
        "Yes","No","Yes","No","No",
        "Yes","Yes","No","No","Yes",
        "Yes","Yes","No","No","Yes",
        "Yes","Yes","No","Yes","Yes"
    ]
}

df = pd.DataFrame(data)
df

,StudentID,Name,Gender,Department,City,Age,Marks,Attendance,Placement
0,101,Ram,Male,CSE,Hyderabad,20,85,92,Yes
1,102,Sita,Female,ECE,Bangalore,21,78,88,No
2,103,John,Male,IT,Chennai,22,90,95,Yes
3,104,Priya,Female,CSE,Mumbai,20,67,75,No
4,105,Arjun,Male,MECH,Hyderabad,23,55,68,No
5,106,Sneha,Female,ECE,Bangalore,21,88,90,Yes
6,107,David,Male,IT,Chennai,22,92,97,Yes
7,108,Kiran,Male,CSE,Mumbai,20,45,60,No
8,109,Ravi,Male,MECH,Hyderabad,23,60,72,No
9,110,Meena,Female,IT,Bangalore,21,73,80,Yes
10,111,Akash,Male,CSE,Chennai,22,95,98,Yes
11,112,Pooja,Female,ECE,Mumbai,20,81,91,Yes
12,113,Rahul,Male,IT,Hyderabad,21,69,77,No
13,114,Divya,Female,MECH,Bangalore,23,58,70,No
14,115,Ramesh,Male,CSE,Chennai,22,84,89,Yes
15,116,Anjali,Female,ECE,Mumbai,20,76,85,Yes
16,117,Vijay,Male,IT,Hyderabad,21,91,96,Yes
17,118,Keerthi,Female,MECH,Bangalore,22,62,74,No
18,119,Karthik,Male,CSE,Chennai,23,87,93,Yes
19,120,Nisha,Female,ECE,Mumbai,20,79,87,Yes

In [15]:
df.head()

,StudentID,Name,Gender,Department,City,Age,Marks,Attendance,Placement
0,101,Ram,Male,CSE,Hyderabad,20,85,92,Yes
1,102,Sita,Female,ECE,Bangalore,21,78,88,No
2,103,John,Male,IT,Chennai,22,90,95,Yes
3,104,Priya,Female,CSE,Mumbai,20,67,75,No
4,105,Arjun,Male,MECH,Hyderabad,23,55,68,No

In [16]:
marks=[40,45,50,55,60,65,70,75,80]

In [17]:
np.mean(marks)

np.float64(60.0)

In [18]:
np.median(marks)

np.float64(60.0)

In [20]:
import numpy as np

data=np.random.normal(70,10,1000)
print(data[:20])

[58.46366968 59.43759154 58.17913728 70.47477513 71.91909886 49.5800323
 76.26309044 87.0292273  70.91217539 75.20450023 76.71513206 67.56331594
 70.07137284 59.51045635 75.90681395 54.61186082 56.14341139 53.60721934
 78.95791761 54.67003412]

In [21]:
#the rule of 68-95-99.7

In [22]:
#suppose mean=70  std =10    one st 60-80  it contains 68% of data

In [23]:
#if we take 2 stds then it will be in bw 50-90  and it contains 95% of the data

In [24]:
#if we take 3 std then the values will be 40-100
# and it contains 99.7% of the data

In [25]:
marks=np.random.normal(
    70,10,1000

)

count=0

for i in marks:
  if 60<=i<=80:
    count+=1
print(count)

print(count/len(marks))

685
0.685

In [26]:
from scipy.stats import ttest_1samp

In [27]:
marks=[75,78,80,82,85,79,81,84,83,80]

In [28]:
t_stat,p_value=ttest_1samp(marks,70)

In [29]:
print("p-value",p_value)

p-value 1.2429983723544405e-06

In [31]:
#here p-value is not less than 0.05 so we cant reject it

In [32]:
from scipy.stats import ttest_1samp
salary=[

        50000,52000,51000,53000,55000,54000,56000,55000,58000
 ]

In [34]:
#test claim average salary=45000

In [35]:
#p-value decision and conclusion

In [38]:
np.mean(salary)
#null hypothesis avg salary=45000
#alt avg salary!=45000

np.float64(53777.77777777778)

In [36]:
t_stat,p=ttest_1samp(salary,45000)

print("p-value",p)

p-value 6.452457577902997e-06

In [39]:
#there is sufficient evidence to conclude that the avg salary is not 45000

In [40]:
#or

In [41]:
# the sample strategy suggests that the actual average salary is different from 45000

In [42]:
import numpy as np

salary=[
    45000,50000,55000,51000,52000,53000,49000,57000
]

In [47]:
mean=np.mean(salary)
mean

np.float64(51500.0)

In [45]:
std=np.std(salary)
std

np.float64(3464.1016151377544)

In [46]:
#mean=51500 now the manual interval shoul be margin=2000

#interval is 49500 - 53500

In [48]:
import numpy as np
from scipy import stats
data=[
    45000,50000,52000,48000,51000,53000,55000,49000,52000
]

confidence=0.95

interval=stats.t.interval(
    confidence,
    len(data)-1,
    loc=np.mean(data),
    scale=stats.sem(data)
)

print(interval)

(np.float64(48278.19854657463), np.float64(52832.91256453648))

In [49]:
import numpy as np
from scipy import stats
salary=np.random.randint(
    30000,100000,100
)

In [50]:
mean_salary=np.mean(salary)

In [51]:
interval=stats.t.interval(
    0.95,
    len(salary)-1,
    loc=mean_salary,
    scale=stats.sem(salary)
)

In [52]:
print("Average_salary",mean_salary)

print("95% confidence interval",interval)

Average_salary 64800.24
95% confidence interval (np.float64(60796.67551605438), np.float64(68803.80448394561))