In [ ]:
import random
coin_toss=[]
for i in range(50):
  coin=random.choice(["head","tail"])
  coin_toss.append(coin)

print(coin_toss)

['head', 'tail', 'tail', 'tail', 'tail', 'head', 'head', 'head', 'tail', 'head', 'head', 'head', 'head', 'tail', 'head', 'head', 'tail', 'head', 'tail', 'tail', 'tail', 'tail', 'head', 'head', 'head', 'head', 'head', 'head', 'head', 'tail', 'head', 'tail', 'head', 'head', 'head', 'tail', 'head', 'head', 'head', 'head', 'head', 'head', 'head', 'tail', 'head', 'tail', 'head', 'head', 'tail', 'head']

In [ ]:
from collections import Counter
print(Counter(coin_toss))

Counter({'head': 33, 'tail': 17})

In [ ]:
dice=random.randint(1,6)

print(dice)

3

In [ ]:
import random

results=[]

for i in range(50):
  results.append(random.randint(1,6))
print(results)

[5, 2, 5, 4, 3, 2, 5, 5, 3, 5, 6, 2, 2, 1, 6, 3, 5, 2, 6, 4, 4, 1, 6, 6, 6, 2, 4, 6, 5, 5, 6, 5, 1, 3, 5, 1, 5, 6, 6, 1, 5, 3, 1, 6, 5, 4, 4, 4, 2, 5]

In [ ]:
from collections import Counter
print(Counter(results))

Counter({5: 14, 6: 11, 2: 7, 4: 7, 1: 6, 3: 5})

event=outcome of interest

getting head    getting tail

In [ ]:
dice=[1,2,3,4,5,6]

In [ ]:
dice=random.randint(1,6)
if dice%2==0:
  print("even event")
else:
  print("odd event")
print(dice)

odd event
3

In [ ]:
import random
coin1=random.choice(["Head","Tail"])

coin2=random.choice(["Head","Tail"])

print(coin1,coin2)

Head Head

In [ ]:
cards=["a","k","q","j"]
first=random.choice(cards)
cards.remove(first)
second=random.choice(cards)
print(first)
print(second)

j
a

In [ ]:
import random
heads=0
tails=0
for i in range(100):
  toss=random.choice(["head","tail"])
  if toss=="head":
    heads+=1
  else:
    tails+=1
print("heads:",heads)
print("tails",tails)
print("probability of head:",heads/100)
print("probability of tail:",tails/100)

heads: 52
tails 48
probability of head: 0.52
probability of tail: 0.48

In [ ]:
import pandas as pd

data={
    "Gender":[
        "Male",
        "Female",
        "Male",
        "Female",
        "Female"
    ],
  "Dept":[
      "CSE",
      "CSE",
      "ECE",
      "ECE",
      "CSE"
   ]
}

df=pd.DataFrame(data)

df

   Gender Dept
0    Male  CSE
1  Female  CSE
2    Male  ECE
3  Female  ECE
4  Female  CSE

In [ ]:
#find the female probability

In [ ]:
female_count=len(df[df["Gender"]=="Female"])

In [ ]:
female_count

3

In [ ]:
total=len(df)

In [ ]:
total

5

In [ ]:
print(female_count/total)

0.6

In [ ]:
cse_students=df[df['Dept']=="CSE"]
female_cse=len(cse_students[cse_students["Gender"]=="Female"])

In [ ]:
female_cse

2

In [ ]:
total_cse=len(cse_students)

In [ ]:
print(female_cse/total_cse)

0.6666666666666666

employee gender dept
a         male   it
b         female it
c         male    hr
d         female   hr
e         female    it
f          male     finance
g          female   finance

In [ ]:
#now we will create the card game simulator

In [ ]:
import random
cards=[]
suits=[
    "Hearts",
    "Diamonds",
    "Clubs",
    "Spades"
]

In [ ]:
ranks=['a','2','3','4','5','6','7','8','9','10','J','Q','K']

In [ ]:
for suit in suits:
  for rank in ranks:
    cards.append(rank+"of"+suit)
  selected=random.choice(cards)
  # print("selected card")
  # if "K" in selected:
  #   print("King of",selected)
  # else:
  #   print("not a king")
print(cards)
len(cards)

['aofHearts', '2ofHearts', '3ofHearts', '4ofHearts', '5ofHearts', '6ofHearts', '7ofHearts', '8ofHearts', '9ofHearts', '10ofHearts', 'JofHearts', 'QofHearts', 'KofHearts', 'aofDiamonds', '2ofDiamonds', '3ofDiamonds', '4ofDiamonds', '5ofDiamonds', '6ofDiamonds', '7ofDiamonds', '8ofDiamonds', '9ofDiamonds', '10ofDiamonds', 'JofDiamonds', 'QofDiamonds', 'KofDiamonds', 'aofClubs', '2ofClubs', '3ofClubs', '4ofClubs', '5ofClubs', '6ofClubs', '7ofClubs', '8ofClubs', '9ofClubs', '10ofClubs', 'JofClubs', 'QofClubs', 'KofClubs', 'aofSpades', '2ofSpades', '3ofSpades', '4ofSpades', '5ofSpades', '6ofSpades', '7ofSpades', '8ofSpades', '9ofSpades', '10ofSpades', 'JofSpades', 'QofSpades', 'KofSpades', 'aofHearts', '2ofHearts', '3ofHearts', '4ofHearts', '5ofHearts', '6ofHearts', '7ofHearts', '8ofHearts', '9ofHearts', '10ofHearts', 'JofHearts', 'QofHearts', 'KofHearts', 'aofDiamonds', '2ofDiamonds', '3ofDiamonds', '4ofDiamonds', '5ofDiamonds', '6ofDiamonds', '7ofDiamonds', '8ofDiamonds', '9ofDiamonds', '10ofDiamonds', 'JofDiamonds', 'QofDiamonds', 'KofDiamonds', 'aofClubs', '2ofClubs', '3ofClubs', '4ofClubs', '5ofClubs', '6ofClubs', '7ofClubs', '8ofClubs', '9ofClubs', '10ofClubs', 'JofClubs', 'QofClubs', 'KofClubs', 'aofSpades', '2ofSpades', '3ofSpades', '4ofSpades', '5ofSpades', '6ofSpades', '7ofSpades', '8ofSpades', '9ofSpades', '10ofSpades', 'JofSpades', 'QofSpades', 'KofSpades', 'aofHearts', '2ofHearts', '3ofHearts', '4ofHearts', '5ofHearts', '6ofHearts', '7ofHearts', '8ofHearts', '9ofHearts', '10ofHearts', 'JofHearts', 'QofHearts', 'KofHearts', 'aofDiamonds', '2ofDiamonds', '3ofDiamonds', '4ofDiamonds', '5ofDiamonds', '6ofDiamonds', '7ofDiamonds', '8ofDiamonds', '9ofDiamonds', '10ofDiamonds', 'JofDiamonds', 'QofDiamonds', 'KofDiamonds', 'aofClubs', '2ofClubs', '3ofClubs', '4ofClubs', '5ofClubs', '6ofClubs', '7ofClubs', '8ofClubs', '9ofClubs', '10ofClubs', 'JofClubs', 'QofClubs', 'KofClubs', 'aofSpades', '2ofSpades', '3ofSpades', '4ofSpades', '5ofSpades', '6ofSpades', '7ofSpades', '8ofSpades', '9ofSpades', '10ofSpades', 'JofSpades', 'QofSpades', 'KofSpades', 'aofHearts', '2ofHearts', '3ofHearts', '4ofHearts', '5ofHearts', '6ofHearts', '7ofHearts', '8ofHearts', '9ofHearts', '10ofHearts', 'JofHearts', 'QofHearts', 'KofHearts', 'aofDiamonds', '2ofDiamonds', '3ofDiamonds', '4ofDiamonds', '5ofDiamonds', '6ofDiamonds', '7ofDiamonds', '8ofDiamonds', '9ofDiamonds', '10ofDiamonds', 'JofDiamonds', 'QofDiamonds', 'KofDiamonds', 'aofClubs', '2ofClubs', '3ofClubs', '4ofClubs', '5ofClubs', '6ofClubs', '7ofClubs', '8ofClubs', '9ofClubs', '10ofClubs', 'JofClubs', 'QofClubs', 'KofClubs', 'aofSpades', '2ofSpades', '3ofSpades', '4ofSpades', '5ofSpades', '6ofSpades', '7ofSpades', '8ofSpades', '9ofSpades', '10ofSpades', 'JofSpades', 'QofSpades', 'KofSpades']

208

In [ ]:
#because we genered each card 4 times and 13 ranks 13X52X4=208

In [ ]:
import random
money=100000000
for round in range(1000):
  print("\n Round",round+1)
  guess=random.choice(["red","black"])
  card_color=random.choice(["red","black"])
  print("player guess",guess)
  print("card color",card_color)
  if guess==card_color:
    money+=1000000
    print("win +100 inr")
  else:
    money-=1000000
    print("you lost 100")
  print("Balance=",money)
print("final balance=",money)

 Round 1
player guess red
card color black
you lost 100
Balance= 99000000

 Round 2
player guess black
card color black
win +100 inr
Balance= 100000000

 Round 3
player guess red
card color black
you lost 100
Balance= 99000000

 Round 4
player guess black
card color black
win +100 inr
Balance= 100000000

 Round 5
player guess black
card color black
win +100 inr
Balance= 101000000

 Round 6
player guess black
card color black
win +100 inr
Balance= 102000000

 Round 7
player guess red
card color black
you lost 100
Balance= 101000000

 Round 8
player guess black
card color red
you lost 100
Balance= 100000000

 Round 9
player guess red
card color red
win +100 inr
Balance= 101000000

 Round 10
player guess black
card color red
you lost 100
Balance= 100000000

 Round 11
player guess black
card color red
you lost 100
Balance= 99000000

 Round 12
player guess red
card color black
you lost 100
Balance= 98000000

 Round 13
player guess red
card color black
you lost 100
Balance= 97000000

 Round 14
player guess black
card color black
win +100 inr
Balance= 98000000

 Round 15
player guess black
card color black
win +100 inr
Balance= 99000000

 Round 16
player guess red
card color black
you lost 100
Balance= 98000000

 Round 17
player guess red
card color black
you lost 100
Balance= 97000000

 Round 18
player guess black
card color red
you lost 100
Balance= 96000000

 Round 19
player guess red
card color red
win +100 inr
Balance= 97000000

 Round 20
player guess black
card color black
win +100 inr
Balance= 98000000

 Round 21
player guess black
card color black
win +100 inr
Balance= 99000000

 Round 22
player guess red
card color black
you lost 100
Balance= 98000000

 Round 23
player guess black
card color black
win +100 inr
Balance= 99000000

 Round 24
player guess black
card color red
you lost 100
Balance= 98000000

 Round 25
player guess red
card color black
you lost 100
Balance= 97000000

 Round 26
player guess red
card color red
win +100 inr
Balance= 98000000

 Round 27
player guess red
card color black
you lost 100
Balance= 97000000

 Round 28
player guess red
card color red
win +100 inr
Balance= 98000000

 Round 29
player guess red
card color red
win +100 inr
Balance= 99000000

 Round 30
player guess red
card color black
you lost 100
Balance= 98000000

 Round 31
player guess red
card color red
win +100 inr
Balance= 99000000

 Round 32
player guess red
card color red
win +100 inr
Balance= 100000000

 Round 33
player guess black
card color black
win +100 inr
Balance= 101000000

 Round 34
player guess black
card color red
you lost 100
Balance= 100000000

 Round 35
player guess red
card color red
win +100 inr
Balance= 101000000

 Round 36
player guess black
card color black
win +100 inr
Balance= 102000000

 Round 37
player guess black
card color red
you lost 100
Balance= 101000000

 Round 38
player guess black
card color red
you lost 100
Balance= 100000000

 Round 39
player guess black
card color red
you lost 100
Balance= 99000000

 Round 40
player guess red
card color black
you lost 100
Balance= 98000000

 Round 41
player guess red
card color black
you lost 100
Balance= 97000000

 Round 42
player guess red
card color black
you lost 100
Balance= 96000000

 Round 43
player guess red
card color red
win +100 inr
Balance= 97000000

 Round 44
player guess red
card color red
win +100 inr
Balance= 98000000

 Round 45
player guess black
card color black
win +100 inr
Balance= 99000000

 Round 46
player guess red
card color black
you lost 100
Balance= 98000000

 Round 47
player guess black
card color black
win +100 inr
Balance= 99000000

 Round 48
player guess black
card color red
you lost 100
Balance= 98000000

 Round 49
player guess black
card color red
you lost 100
Balance= 97000000

 Round 50
player guess black
card color red
you lost 100
Balance= 96000000

 Round 51
player guess red
card color red
win +100 inr
Balance= 97000000

 Round 52
player guess red
card color black
you lost 100
Balance= 96000000

 Round 53
player guess black
card color red
you lost 100
Balance= 95000000

 Round 54
player guess red
card color black
you lost 100
Balance= 94000000

 Round 55
player guess red
card color black
you lost 100
Balance= 93000000

 Round 56
player guess red
card color black
you lost 100
Balance= 92000000

 Round 57
player guess black
card color black
win +100 inr
Balance= 93000000

 Round 58
player guess black
card color red
you lost 100
Balance= 92000000

 Round 59
player guess red
card color red
win +100 inr
Balance= 93000000

 Round 60
player guess red
card color black
you lost 100
Balance= 92000000

 Round 61
player guess black
card color black
win +100 inr
Balance= 93000000

 Round 62
player guess black
card color black
win +100 inr
Balance= 94000000

 Round 63
player guess red
card color red
win +100 inr
Balance= 95000000

 Round 64
player guess black
card color black
win +100 inr
Balance= 96000000

 Round 65
player guess black
card color red
you lost 100
Balance= 95000000

 Round 66
player guess black
card color red
you lost 100
Balance= 94000000

 Round 67
player guess black
card color black
win +100 inr
Balance= 95000000

 Round 68
player guess black
card color red
you lost 100
Balance= 94000000

 Round 69
player guess black
card color black
win +100 inr
Balance= 95000000

 Round 70
player guess black
card color red
you lost 100
Balance= 94000000

 Round 71
player guess red
card color black
you lost 100
Balance= 93000000

 Round 72
player guess black
card color red
you lost 100
Balance= 92000000

 Round 73
player guess black
card color red
you lost 100
Balance= 91000000

 Round 74
player guess red
card color red
win +100 inr
Balance= 92000000

 Round 75
player guess red
card color black
you lost 100
Balance= 91000000

 Round 76
player guess red
card color red
win +100 inr
Balance= 92000000

 Round 77
player guess red
card color red
win +100 inr
Balance= 93000000

 Round 78
player guess black
card color red
you lost 100
Balance= 92000000

 Round 79
player guess red
card color black
you lost 100
Balance= 91000000

 Round 80
player guess black
card color black
win +100 inr
Balance= 92000000

 Round 81
player guess red
card color red
win +100 inr
Balance= 93000000

 Round 82
player guess black
card color red
you lost 100
Balance= 92000000

 Round 83
player guess red
card color black
you lost 100
Balance= 91000000

 Round 84
player guess black
card color red
you lost 100
Balance= 90000000

 Round 85
player guess red
card color black
you lost 100
Balance= 89000000

 Round 86
player guess black
card color red
you lost 100
Balance= 88000000

 Round 87
player guess red
card color black
you lost 100
Balance= 87000000

 Round 88
player guess red
card color black
you lost 100
Balance= 86000000

 Round 89
player guess red
card color black
you lost 100
Balance= 85000000

 Round 90
player guess black
card color red
you lost 100
Balance= 84000000

 Round 91
player guess red
card color red
win +100 inr
Balance= 85000000

 Round 92
player guess red
card color red
win +100 inr
Balance= 86000000

 Round 93
player guess black
card color black
win +100 inr
Balance= 87000000

 Round 94
player guess red
card color black
you lost 100
Balance= 86000000

 Round 95
player guess red
card color red
win +100 inr
Balance= 87000000

 Round 96
player guess red
card color red
win +100 inr
Balance= 88000000

 Round 97
player guess red
card color black
you lost 100
Balance= 87000000

 Round 98
player guess black
card color red
you lost 100
Balance= 86000000

 Round 99
player guess black
card color black
win +100 inr
Balance= 87000000

 Round 100
player guess black
card color black
win +100 inr
Balance= 88000000

 Round 101
player guess red
card color black
you lost 100
Balance= 87000000

 Round 102
player guess red
card color black
you lost 100
Balance= 86000000

 Round 103
player guess red
card color black
you lost 100
Balance= 85000000

 Round 104
player guess black
card color red
you lost 100
Balance= 84000000

 Round 105
player guess black
card color black
win +100 inr
Balance= 85000000

 Round 106
player guess black
card color black
win +100 inr
Balance= 86000000

 Round 107
player guess black
card color black
win +100 inr
Balance= 87000000

 Round 108
player guess red
card color red
win +100 inr
Balance= 88000000

 Round 109
player guess red
card color black
you lost 100
Balance= 87000000

 Round 110
player guess black
card color red
you lost 100
Balance= 86000000

 Round 111
player guess red
card color black
you lost 100
Balance= 85000000

 Round 112
player guess red
card color black
you lost 100
Balance= 84000000

 Round 113
player guess black
card color red
you lost 100
Balance= 83000000

 Round 114
player guess black
card color black
win +100 inr
Balance= 84000000

 Round 115
player guess red
card color black
you lost 100
Balance= 83000000

 Round 116
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 117
player guess red
card color red
win +100 inr
Balance= 85000000

 Round 118
player guess black
card color red
you lost 100
Balance= 84000000

 Round 119
player guess black
card color red
you lost 100
Balance= 83000000

 Round 120
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 121
player guess black
card color red
you lost 100
Balance= 83000000

 Round 122
player guess red
card color black
you lost 100
Balance= 82000000

 Round 123
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 124
player guess red
card color black
you lost 100
Balance= 82000000

 Round 125
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 126
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 127
player guess red
card color black
you lost 100
Balance= 83000000

 Round 128
player guess black
card color red
you lost 100
Balance= 82000000

 Round 129
player guess red
card color red
win +100 inr
Balance= 83000000

 Round 130
player guess red
card color black
you lost 100
Balance= 82000000

 Round 131
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 132
player guess black
card color red
you lost 100
Balance= 82000000

 Round 133
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 134
player guess black
card color black
win +100 inr
Balance= 84000000

 Round 135
player guess black
card color red
you lost 100
Balance= 83000000

 Round 136
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 137
player guess red
card color black
you lost 100
Balance= 83000000

 Round 138
player guess black
card color red
you lost 100
Balance= 82000000

 Round 139
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 140
player guess red
card color black
you lost 100
Balance= 82000000

 Round 141
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 142
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 143
player guess red
card color black
you lost 100
Balance= 83000000

 Round 144
player guess red
card color black
you lost 100
Balance= 82000000

 Round 145
player guess black
card color red
you lost 100
Balance= 81000000

 Round 146
player guess black
card color black
win +100 inr
Balance= 82000000

 Round 147
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 148
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 149
player guess red
card color black
you lost 100
Balance= 83000000

 Round 150
player guess red
card color black
you lost 100
Balance= 82000000

 Round 151
player guess red
card color black
you lost 100
Balance= 81000000

 Round 152
player guess black
card color black
win +100 inr
Balance= 82000000

 Round 153
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 154
player guess black
card color black
win +100 inr
Balance= 84000000

 Round 155
player guess black
card color red
you lost 100
Balance= 83000000

 Round 156
player guess black
card color red
you lost 100
Balance= 82000000

 Round 157
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 158
player guess red
card color black
you lost 100
Balance= 82000000

 Round 159
player guess black
card color red
you lost 100
Balance= 81000000

 Round 160
player guess black
card color black
win +100 inr
Balance= 82000000

 Round 161
player guess red
card color red
win +100 inr
Balance= 83000000

 Round 162
player guess black
card color black
win +100 inr
Balance= 84000000

 Round 163
player guess black
card color black
win +100 inr
Balance= 85000000

 Round 164
player guess black
card color red
you lost 100
Balance= 84000000

 Round 165
player guess red
card color black
you lost 100
Balance= 83000000

 Round 166
player guess red
card color black
you lost 100
Balance= 82000000

 Round 167
player guess red
card color black
you lost 100
Balance= 81000000

 Round 168
player guess red
card color red
win +100 inr
Balance= 82000000

 Round 169
player guess black
card color red
you lost 100
Balance= 81000000

 Round 170
player guess black
card color red
you lost 100
Balance= 80000000

 Round 171
player guess red
card color red
win +100 inr
Balance= 81000000

 Round 172
player guess red
card color red
win +100 inr
Balance= 82000000

 Round 173
player guess black
card color black
win +100 inr
Balance= 83000000

 Round 174
player guess black
card color red
you lost 100
Balance= 82000000

 Round 175
player guess black
card color red
you lost 100
Balance= 81000000

 Round 176
player guess red
card color black
you lost 100
Balance= 80000000

 Round 177
player guess black
card color red
you lost 100
Balance= 79000000

 Round 178
player guess black
card color black
win +100 inr
Balance= 80000000

 Round 179
player guess red
card color red
win +100 inr
Balance= 81000000

 Round 180
player guess black
card color black
win +100 inr
Balance= 82000000

 Round 181
player guess red
card color red
win +100 inr
Balance= 83000000

 Round 182
player guess red
card color red
win +100 inr
Balance= 84000000

 Round 183
player guess black
card color red
you lost 100
Balance= 83000000

 Round 184
player guess red
card color black
you lost 100
Balance= 82000000

 Round 185
player guess black
card color red
you lost 100
Balance= 81000000

 Round 186
player guess red
card color black
you lost 100
Balance= 80000000

 Round 187
player guess red
card color black
you lost 100
Balance= 79000000

 Round 188
player guess red
card color red
win +100 inr
Balance= 80000000

 Round 189
player guess red
card color black
you lost 100
Balance= 79000000

 Round 190
player guess black
card color red
you lost 100
Balance= 78000000

 Round 191
player guess black
card color black
win +100 inr
Balance= 79000000

 Round 192
player guess black
card color black
win +100 inr
Balance= 80000000

 Round 193
player guess red
card color red
win +100 inr
Balance= 81000000

 Round 194
player guess black
card color black
win +100 inr
Balance= 82000000

 Round 195
player guess red
card color black
you lost 100
Balance= 81000000

 Round 196
player guess red
card color black
you lost 100
Balance= 80000000

 Round 197
player guess black
card color red
you lost 100
Balance= 79000000

 Round 198
player guess red
card color red
win +100 inr
Balance= 80000000

 Round 199
player guess black
card color red
you lost 100
Balance= 79000000

 Round 200
player guess black
card color red
you lost 100
Balance= 78000000

 Round 201
player guess black
card color black
win +100 inr
Balance= 79000000

 Round 202
player guess red
card color red
win +100 inr
Balance= 80000000

 Round 203
player guess red
card color red
win +100 inr
Balance= 81000000

 Round 204
player guess red
card color red
win +100 inr
Balance= 82000000

 Round 205
player guess red
card color black
you lost 100
Balance= 81000000

 Round 206
player guess red
card color black
you lost 100
Balance= 80000000

 Round 207
player guess red
card color black
you lost 100
Balance= 79000000

 Round 208
player guess black
card color black
win +100 inr
Balance= 80000000

 Round 209
player guess red
card color red
win +100 inr
Balance= 81000000

 Round 210
player guess red
card color black
you lost 100
Balance= 80000000

 Round 211
player guess red
card color black
you lost 100
Balance= 79000000

 Round 212
player guess red
card color black
you lost 100
Balance= 78000000

 Round 213
player guess black
card color red
you lost 100
Balance= 77000000

 Round 214
player guess black
card color red
you lost 100
Balance= 76000000

 Round 215
player guess red
card color black
you lost 100
Balance= 75000000

 Round 216
player guess black
card color red
you lost 100
Balance= 74000000

 Round 217
player guess red
card color black
you lost 100
Balance= 73000000

 Round 218
player guess red
card color black
you lost 100
Balance= 72000000

 Round 219
player guess black
card color black
win +100 inr
Balance= 73000000

 Round 220
player guess black
card color black
win +100 inr
Balance= 74000000

 Round 221
player guess black
card color black
win +100 inr
Balance= 75000000

 Round 222
player guess red
card color black
you lost 100
Balance= 74000000

 Round 223
player guess red
card color black
you lost 100
Balance= 73000000

 Round 224
player guess black
card color black
win +100 inr
Balance= 74000000

 Round 225
player guess black
card color black
win +100 inr
Balance= 75000000

 Round 226
player guess red
card color black
you lost 100
Balance= 74000000

 Round 227
player guess black
card color red
you lost 100
Balance= 73000000

 Round 228
player guess black
card color red
you lost 100
Balance= 72000000

 Round 229
player guess red
card color red
win +100 inr
Balance= 73000000

 Round 230
player guess red
card color black
you lost 100
Balance= 72000000

 Round 231
player guess red
card color black
you lost 100
Balance= 71000000

 Round 232
player guess red
card color red
win +100 inr
Balance= 72000000

 Round 233
player guess red
card color black
you lost 100
Balance= 71000000

 Round 234
player guess black
card color red
you lost 100
Balance= 70000000

 Round 235
player guess black
card color red
you lost 100
Balance= 69000000

 Round 236
player guess black
card color black
win +100 inr
Balance= 70000000

 Round 237
player guess black
card color red
you lost 100
Balance= 69000000

 Round 238
player guess black
card color red
you lost 100
Balance= 68000000

 Round 239
player guess black
card color black
win +100 inr
Balance= 69000000

 Round 240
player guess black
card color red
you lost 100
Balance= 68000000

 Round 241
player guess red
card color red
win +100 inr
Balance= 69000000

 Round 242
player guess black
card color black
win +100 inr
Balance= 70000000

 Round 243
player guess black
card color black
win +100 inr
Balance= 71000000

 Round 244
player guess red
card color red
win +100 inr
Balance= 72000000

 Round 245
player guess red
card color black
you lost 100
Balance= 71000000

 Round 246
player guess black
card color black
win +100 inr
Balance= 72000000

 Round 247
player guess red
card color red
win +100 inr
Balance= 73000000

 Round 248
player guess black
card color red
you lost 100
Balance= 72000000

 Round 249
player guess black
card color red
you lost 100
Balance= 71000000

 Round 250
player guess red
card color black
you lost 100
Balance= 70000000

 Round 251
player guess red
card color black
you lost 100
Balance= 69000000

 Round 252
player guess red
card color red
win +100 inr
Balance= 70000000

 Round 253
player guess red
card color black
you lost 100
Balance= 69000000

 Round 254
player guess red
card color red
win +100 inr
Balance= 70000000

 Round 255
player guess red
card color black
you lost 100
Balance= 69000000

 Round 256
player guess black
card color black
win +100 inr
Balance= 70000000

 Round 257
player guess red
card color black
you lost 100
Balance= 69000000

 Round 258
player guess black
card color red
you lost 100
Balance= 68000000

 Round 259
player guess black
card color red
you lost 100
Balance= 67000000

 Round 260
player guess red
card color red
win +100 inr
Balance= 68000000

 Round 261
player guess red
card color black

In [ ]:
import random
cards=['a','2','3','4','5','6','7','8','9','10','J','Q','K']

In [ ]:
score={
    'a':14,
    'K':13,
    'Q':12,
    'J':11,
    '10':10,
    '9':9,
    '8':8,
    '7':7,
    '6':6,
    '5':5,
    '4':4,
    '3':3,
    '2':2
 }

In [ ]:
player_wins=0
computer_wins=0
for round in range(20):
  player=random.choice(cards)
  computer=random.choice(cards)
  print("\nround",round+1)
  print("player card",player)
  print("computer",computer)
  if score[player]>score[computer]:
    print("Player wins")
    player_wins+=1
  elif score[player]<score[computer]:
    print("computer wins")
    computer_wins+=1
  else:
    print("Tie")
print("\n player wins=",player_wins)
print("computer wins=",computer_wins)

round 1
player card 7
computer 3
Player wins

round 2
player card 5
computer 2
Player wins

round 3
player card 2
computer K
computer wins

round 4
player card 10
computer 10
Tie

round 5
player card 5
computer 9
computer wins

round 6
player card 9
computer 5
Player wins

round 7
player card 6
computer K
computer wins

round 8
player card J
computer 3
Player wins

round 9
player card 3
computer a
computer wins

round 10
player card 4
computer K
computer wins

round 11
player card 10
computer K
computer wins

round 12
player card J
computer 10
Player wins

round 13
player card 3
computer 10
computer wins

round 14
player card 3
computer 7
computer wins

round 15
player card K
computer 9
Player wins

round 16
player card Q
computer 5
Player wins

round 17
player card 3
computer 6
computer wins

round 18
player card a
computer Q
Player wins

round 19
player card 7
computer 4
Player wins

round 20
player card 3
computer Q
computer wins

 player wins= 9
computer wins= 10

In [ ]:
#population vs sample

In [ ]:
# college:5000 people

In [ ]:
#entire population is 5000
# if we select 200 students then its called sample

In [ ]:
import pandas as pd
students=[]
for i in range(1,101):
  students.append("students"+str(i))
df=pd.DataFrame({
    "Student":students
})

df

        Student
0     students1
1     students2
2     students3
3     students4
4     students5
..          ...
95   students96
96   students97
97   students98
98   students99
99  students100

[100 rows x 1 columns]

In [ ]:
sample=df.sample(10)

print(sample)

       Student
38  students39
28  students29
40  students41
34  students35
44  students45
31  students32
55  students56
61  students62
95  students96
82  students83

In [ ]:
df.sample(10,random_state=40)

       Student
79  students80
75  students76
63  students64
15  students16
38  students39
11  students12
40  students41
45  students46
39  students40
62  students63

In [ ]:
systematic=df.iloc[::5]
print(systematic)

       Student
0    students1
5    students6
10  students11
15  students16
20  students21
25  students26
30  students31
35  students36
40  students41
45  students46
50  students51
55  students56
60  students61
65  students66
70  students71
75  students76
80  students81
85  students86
90  students91
95  students96

In [ ]:
import pandas as pd
data={
    "Gender":[
        'male',
        'male',
        'male',
        'male',
        'male',
        'female',
        'female',
        'female',
        'female',
        'female',
        'male',
        'male',
        'male',
        'male',
        'male',
        'female',
        'female',
        'female',
        'female',
        'female'
    ]
}

In [ ]:
df=pd.DataFrame(data)
df

    Gender
0     male
1     male
2     male
3     male
4     male
5   female
6   female
7   female
8   female
9   female
10    male
11    male
12    male
13    male
14    male
15  female
16  female
17  female
18  female
19  female

In [ ]:
print(df['Gender'].value_counts())

Gender
male      10
female    10
Name: count, dtype: int64

In [ ]:
import pandas as pd
import random
records=[]
for i in range(1,501):
  gender=random.choice([
      "male",
      'female'
  ])

  department=random.choice([
      "cse",
      "ece",
      "it"
  ])
  records.append(
      [
          i,
          gender,
          department
      ]
   )

In [ ]:
df=pd.DataFrame(
    records,
    columns=[
        "id",
        "gender",
        "department"
     ]
)

df.head()

   id  gender department
0   1    male        ece
1   2    male         it
2   3    male         it
3   4  female        ece
4   5    male         it

In [ ]:
print(

      "population size:",
      len(df)
 )

population size: 500

In [ ]:
random_sample=df.sample(20)

In [ ]:
print(random_sample)

      id  gender department
444  445  female        ece
228  229  female        ece
180  181    male        ece
202  203  female         it
108  109  female        ece
139  140  female        cse
389  390    male        cse
107  108  female        cse
355  356  female        ece
274  275    male         it
205  206    male        cse
363  364  female         it
329  330  female         it
443  444  female         it
16    17    male        ece
409  410  female        ece
313  314  female        ece
137  138    male         it
267  268  female        ece
18    19    male        cse

In [ ]:
systematic_sample=df.iloc[::20]

In [ ]:
systematic_sample

      id  gender department
0      1    male        ece
20    21    male        ece
40    41    male         it
60    61    male        ece
80    81    male        ece
100  101  female         it
120  121  female        ece
140  141    male        ece
160  161    male        ece
180  181    male        ece
200  201    male        cse
220  221    male        cse
240  241    male        ece
260  261    male         it
280  281  female        cse
300  301    male        ece
320  321  female        cse
340  341    male        ece
360  361  female        cse
380  381    male        cse
400  401  female         it
420  421  female        cse
440  441  female        ece
460  461    male         it
480  481  female        cse